const pages = {
  overview: () => `
    <section class="landing-hero">
      <div class="landing-intro"><span class="hero-kicker">NETWORK FOR INTELLIGENCE ON CHILDHOOD, INFORMATION & AI</span><h1>Inteligencia mundial<br>para proteger lo<br>que más importa.</h1><p>Investigamos. Analizamos. Comunicamos. Formamos.<br>Transformamos evidencia en decisiones y acción.</p><form class="landing-search" id="heroSearch"><span>⌕</span><input aria-label="Pregunta para NINIA" placeholder="¿Qué deseas investigar?"><button>Investigar</button></form><small>Ejemplo: ¿Cómo están enfrentando Finlandia y Australia el ciberacoso escolar?</small><div class="landing-shortcuts"><button data-page="observatory">◎ Explorar Observatorio</button><button data-page="packages">▤ Ver Knowledge Packages</button><button>ⓘ Conocer NINIA</button></div></div>
      <article class="featured-story"><img src="assets/ninia-family-hero.png" alt="Familia explorando contenido educativo en una tableta"><div class="story-shade"></div><div class="story-copy"><div><span class="story-tag">TEMA DESTACADO</span><span class="story-tag outline">NUEVA EVIDENCIA</span></div><h2>Involucrar a las familias reduce significativamente el riesgo de ciberacoso en adolescentes</h2><p>Un estudio longitudinal en 12 países demuestra que la participación familiar activa puede reducir hasta un 35% el riesgo de ciberacoso.</p><footer><span>◎ 12 países</span><span>▣ Mayo 2026</span><span>♢ Nivel de evidencia <b>★★★★★</b></span></footer></div><button class="story-button" data-page="library">Ver investigación →</button></article>
    </section>
    <div class="carousel-dots"><i class="active"></i><i></i><i></i><i></i></div>
    <section class="impact-strip">${impact('◎','196','Países monitoreados','Ver mapa →','blue')}${impact('▣','2.540','Fuentes monitoreadas','Ver fuentes →','green')}${impact('△','56.812','Investigaciones analizadas','Explorar →','purple')}${impact('♙','3.247','Programas y estrategias','Ver programas →','orange')}${impact('⌁','24/7','Observatorio activo','En tiempo real →','blue')}</section>
    <section class="evidence-layout">
      <article class="home-card working"><div class="home-title"><h2>¿Qué está funcionando?</h2><button data-page="library">Ver todas →</button></div><div class="practice-grid">${practice('Formación docente continua en bienestar digital','Finlandia · 17 estudios','high','▤')}${practice('Protocolos escolares de respuesta','Australia · 9 evaluaciones','high','◫')}${practice('Participación activa de familias','Canadá · 14 estudios','medium','⌂')}${practice('Diseño seguro de plataformas','Unión Europea · 11 estudios','high','♢')}</div></article>
      <article class="home-card not-working"><div class="home-title"><h2>¿Qué NO está funcionando?</h2><button>Ver todas →</button></div>${failure('Campañas aisladas sin continuidad','Sin impacto medible a mediano plazo. · 12 estudios lo confirman')}${failure('Charlas únicas en instituciones educativas','No generan cambios sostenidos. · 9 evaluaciones lo demuestran')}${failure('Controles parentales sin acompañamiento','Pueden generar falsa sensación de seguridad. · 7 estudios lo evidencian')}${failure('Formación sin evaluación','Sin medición, no hay mejora. · 11 estudios lo confirman')}</article>
      <article class="home-card live-panel"><div class="home-title"><h2>Observatorio en tiempo real</h2><button data-page="observatory">Ver todas →</button></div>${liveItem('Hace 2 horas','UNESCO publica nueva guía sobre IA y protección infantil','blue')}${liveItem('Hace 5 horas','Australia actualiza su estrategia nacional de bienestar digital','green')}${liveItem('Ayer','Nueva revisión sistemática sobre salud mental y redes sociales','lime')}${liveItem('Hace 2 días','Finlandia incorpora inteligencia artificial responsable en educación','green')}${liveItem('Hace 3 días','UNICEF lanza marco global para entornos digitales seguros','red')}</article>
    </section>
    <section class="lower-layout"><article class="home-card package-panel"><div class="home-title"><h2>Knowledge Packages recientes</h2><button data-page="packages">Ver todos →</button></div><div class="package-grid">${packageMini('Salud mental y redes sociales en adolescentes','Mayo 2026')}${packageMini('Regulación de plataformas y protección infantil','Mayo 2026')}${packageMini('Educación digital integral en entornos escolares','Abril 2026')}${packageMini('Inteligencia artificial y derechos de infancia','Abril 2026')}</div></article><article class="home-card org-panel"><div class="home-title"><h2>Organizaciones monitoreadas</h2><button>Ver todas →</button></div><div class="org-grid"><b>UNESCO</b><b>unicef</b><b>WHO</b><b>OECD</b><b>European Commission</b><b>WeProtect</b><b>ECPAT</b><b>ITU</b></div></article><article class="newsletter"><div><h2>Recibe lo más importante</h2><p>Boletín semanal con evidencia, análisis y recomendaciones clave.</p></div><form id="newsletterForm"><input type="email" aria-label="Correo electrónico" placeholder="Tu correo electrónico"><button>Suscribirme</button></form></article></section>
    `,
  observatory: () => `
    <section class="page-header"><div><p class="eyebrow">Observatorio global</p><h1>Riesgos y respuesta digital</h1><p>Monitoreo comparado en tiempo casi real de 193 países y 648 indicadores.</p></div><div class="header-actions"><button class="ghost-button">Exportar ↓</button><button class="primary-button">+ Crear alerta</button></div></section>
    <div class="filter-strip"><button class="filter-button active">Vista global</button><button class="filter-button">Región ⌄</button><button class="filter-button">Tema ⌄</button><button class="filter-button">2020—2026 ⌄</button><button class="filter-button">Nivel de evidencia ⌄</button></div>
    <section class="grid kpi-grid">${kpi('Índice global','67.4','+2.1 vs. 2025','◎')}${kpi('Cobertura de políticas','71%','+6 países','◇')}${kpi('Riesgo emergente','Medio','3 señales críticas','!')}${kpi('Calidad de evidencia','82%','Alta confianza','✓')}</section>
    <section class="grid section-grid"><article class="card map-card"><div class="card-header"><div><h3>Índice de protección digital</h3><p>Selecciona un país para abrir su perfil</p></div><button>Capas ⌄</button></div><div class="map-wrap" style="min-height:360px"><div class="world-map"></div><i class="map-dot d1"></i><i class="map-dot d2"></i><i class="map-dot d3"></i><i class="map-dot d4"></i><i class="map-dot d5"></i><div class="map-legend"><i style="background:#10a37f"></i>70–100 <i style="background:#d99715"></i>40–69 <i style="background:#d94c4c"></i>0–39</div></div></article><article class="card chart-card"><div class="card-header"><div><h3>Evolución del índice</h3><p>Promedio global · 2020—2026</p></div><button>Comparar +</button></div><div class="bar-chart" style="height:330px">${[105,132,146,171,198,228,254].map((v,i)=>`<i class="bar ${i===6?'active':''}" style="height:${v}px" data-label="${2020+i}"></i>`).join('')}</div></article></section>
    <article class="card table-card" style="margin-top:16px"><div class="card-header"><div><h3>Ranking de preparación nacional</h3><p>Indicadores normalizados por disponibilidad de datos</p></div><button>Metodología ↗</button></div><div class="table-toolbar"><input id="countrySearch" placeholder="Buscar país…"><button class="filter-button">Región ⌄</button></div>${countryTable()}</article>`,
  researcher: () => `
    <section class="page-header"><div><p class="eyebrow">Investigador IA</p><h1>Asistente científico</h1></div><div class="header-actions"><button class="ghost-button" id="exportChat">Exportar conversación ↓</button></div></section>
    <section class="researcher-layout"><aside class="chat-history"><button id="newChat">＋ Nueva conversación</button><p class="history-label">Recientes</p><div class="history-item active">Impacto de algoritmos de recomendación</div><div class="history-item">Evidencia sobre verificación de edad</div><div class="history-item">Comparativa regulatoria LATAM</div><p class="history-label">Hace 30 días</p><div class="history-item">Bienestar digital y escuelas</div></aside><div class="chat-main"><div class="chat-intro" id="chatIntro"><div class="ai-badge">✦</div><h2>Investiga con toda la evidencia de NINIA</h2><p>Respuestas sintetizadas, verificables y con citas a fuentes primarias. La IA puede equivocarse; revisa siempre la evidencia.</p><div class="suggestions"><button>¿Qué políticas reducen el acoso digital escolar?</button><button>Compara la regulación de edad en UE y LATAM</button><button>Resume la evidencia sobre redes sociales y sueño</button><button>Identifica vacíos de investigación en IA generativa</button></div></div><div class="chat-messages" id="chatMessages"></div><form class="chat-composer" id="chatForm"><input id="chatInput" placeholder="Haz una pregunta de investigación…" autocomplete="off"><button aria-label="Enviar">↑</button></form></div><aside class="source-panel"><h3>Fuentes y contexto</h3><div id="sourceList"><div class="empty-source">Las fuentes citadas y documentos relacionados aparecerán aquí.</div></div></aside></section>`,
  library: () => `
    <section class="page-header"><div><p class="eyebrow">Biblioteca de evidencia</p><h1>12.486 documentos indexados</h1><p>Investigación académica, políticas públicas y datos globales, clasificados por IA y revisados con criterios transparentes.</p><div class="library-stats"><span><b>87%</b> texto completo</span><span><b>64</b> idiomas</span><span><b>1.240</b> organizaciones</span></div></div><button class="primary-button">＋ Añadir fuente</button></section>
    <div class="filter-strip"><button class="filter-button active">Toda la evidencia</button><button class="filter-button">País ⌄</button><button class="filter-button">Tema ⌄</button><button class="filter-button">Tipo de estudio ⌄</button><button class="filter-button">Evidencia ⌄</button><button class="filter-button">Fecha ⌄</button></div>
    <div class="table-toolbar card" style="padding:10px;margin-bottom:16px"><input id="paperSearch" placeholder="Buscar por título, autor, organización o palabra clave…"><button class="filter-button">Más filtros ≡</button></div>
    <section class="library-grid" id="paperGrid">${paperCards()}</section>`,
};

const labels={compare:['Comparador','Compara políticas, programas, países e investigaciones en una misma vista.','⇄',['País vs. país','Indicadores alineados','Exportación ejecutiva']],trends:['Tendencias y prospectiva','Modelos predictivos, series de tiempo y alertas tempranas con trazabilidad.','⌁',['Señales emergentes','Escenarios futuros','Modelos predictivos']],media:['Media Intelligence','Monitoreo internacional de noticias, redes, podcasts, video y desinformación.','◫',['Sentimiento global','Narrativas coordinadas','Mapa de cobertura']],packages:['Knowledge Packages','Productos de conocimiento listos para la decisión, con evidencia, casos y recomendaciones.','◇',['Resumen ejecutivo','Recomendaciones','Bibliografía trazable']],studio:['AI Studio','Laboratorio para modelos, clasificadores, embeddings, OCR y pipelines RAG.','⌘',['Registro de modelos','Estado de pipelines','Evaluaciones']],academy:['NINIA Academy','Formación especializada para investigadores, reguladores y responsables de políticas.','△',['Rutas de aprendizaje','Microlearning','Certificaciones']]};
Object.entries(labels).forEach(([key,v])=>pages[key]=()=>`<section class="page-header"><div><p class="eyebrow">NINIA PLATFORM</p><h1>${v[0]}</h1><p>${v[1]}</p></div><button class="primary-button">Crear nuevo +</button></section><section class="skeleton-page card"><div class="skeleton-icon">${v[2]}</div><h2>${v[0]}</h2><p>${v[1]} Este módulo forma parte del mismo sistema de inteligencia y conserva navegación, filtros, fuentes y asistente contextual.</p><div class="skeleton-modules">${v[3].map(x=>`<span>${x} →</span>`).join('')}</div></section>`);

function kpi(label,value,trend,icon){return `<article class="card kpi-card"><div class="kpi-head"><span>${label}</span><i class="kpi-icon">${icon}</i></div><div class="kpi-value">${value}</div><span class="trend-up">${trend}</span></article>`}
function impact(icon,value,label,link,color){return `<article class="impact-item"><i class="impact-icon ${color}">${icon}</i><div><b>${value}</b><span>${label}</span><button>${link}</button></div></article>`}
function practice(title,meta,level,icon){return `<div class="practice"><div class="practice-image p-${icon.charCodeAt(0)%4}"><span>★★★★★</span><i>${icon}</i></div><h3>${title}</h3><p>${meta}</p><em class="evidence ${level==='high'?'high':'medium'}">Evidencia ${level==='high'?'alta':'media'}</em></div>`}
function failure(title,desc){return `<div class="failure"><i>×</i><div><h3>${title}</h3><p>${desc}</p></div></div>`}
function liveItem(time,title,color){return `<div class="live-item"><i class="${color}"></i><div><small>${time}</small><h3>${title}</h3></div></div>`}
function packageMini(title,date){return `<div class="package-mini"><h3>${title}</h3><p>▣ ${date} <b>★★★★★</b> <em>Nuevo</em></p><button>Explorar →</button></div>`}
function researchItems(){return [['Diseño seguro por edad: una revisión sistemática','UNICEF Innocenti · 2026','Alta'],['Adolescentes e IA generativa: oportunidades y riesgos','Nature Human Behaviour · 2026','Alta'],['Efectividad de controles parentales en plataformas','OECD Digital Economy · 2025','Media']].map(x=>`<div class="research-item"><span class="doc-icon">▤</span><div><h4>${x[0]}</h4><span class="meta">${x[1]}</span></div><span class="evidence ${x[2]==='Alta'?'high':'medium'}">${x[2]}</span></div>`).join('')}
function alertItem(t,d,time){return `<div class="alert-item"><span class="alert-symbol">!</span><div><h4>${t}</h4><p>${d}</p></div><span class="alert-time">${time}</span></div>`}
function countryTable(){const rows=[['1','Finlandia','92.4','↑ 2','Europa'],['2','Suecia','90.8','—','Europa'],['3','Canadá','89.7','↑ 1','Norteamérica'],['4','Australia','88.9','↓ 1','Oceanía'],['5','Uruguay','84.2','↑ 4','Latinoamérica']];return `<table><thead><tr><th>Pos.</th><th>País</th><th>Índice</th><th>Cambio</th><th>Región</th><th>Evidencia</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${r[0]}</td><td><span class="country"><i class="flag"></i>${r[1]}</span></td><td class="score">${r[2]}</td><td class="${r[3].includes('↑')?'rank-up':r[3].includes('↓')?'rank-down':''}">${r[3]}</td><td>${r[4]}</td><td><span class="evidence high">Alta</span></td></tr>`).join('')}</tbody></table>`}
function paperCards(){return [['Revisión sistemática','Safety by design for children: global evidence review','UNICEF Innocenti','Analiza 84 intervenciones de diseño y sus efectos sobre exposición, privacidad y bienestar.','Alta'],['Estudio longitudinal','Social media, sleep and adolescent wellbeing','Nature Human Behaviour','Seguimiento de 6.400 adolescentes durante cuatro años en siete países.','Alta'],['Policy brief','Age assurance: regulatory approaches in 32 countries','OECD','Comparación de modelos regulatorios, implementación y garantías de privacidad.','Media'],['Meta-análisis','Cyberbullying prevention in school settings','JAMA Pediatrics','Efectividad comparada de programas escolares en 18 sistemas educativos.','Alta'],['Datos','Global Kids Online: 2026 indicators','UNICEF · LSE','Indicadores armonizados de acceso, habilidades, oportunidades y riesgos digitales.','Alta'],['Working paper','Generative AI companions and minors','MIT Media Lab','Señales emergentes sobre dependencia, confianza y antropomorfización.','Baja']].map((x,i)=>`<article class="card paper-card"><div class="paper-top"><span class="paper-type">${x[0]}</span><button class="save-button" aria-label="Guardar investigación">♡</button></div><h3>${x[1]}</h3><p>${x[3]}</p><div class="paper-footer"><span class="meta">${x[2]} · 2026</span><span class="evidence ${x[4]==='Alta'?'high':x[4]==='Media'?'medium':'low'}">${x[4]}</span></div></article>`).join('')}

const content=document.getElementById('pageContent');
function navigate(page){page=pages[page]?page:'overview';content.innerHTML=pages[page]();document.querySelectorAll('.public-nav [data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));document.getElementById('sidebar').classList.remove('open');window.location.hash=page;window.scrollTo(0,0);bindPageEvents(page)}
function bindPageEvents(page){content.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));content.querySelectorAll('.filter-button').forEach(b=>b.onclick=()=>{b.classList.toggle('active');showToast(b.classList.contains('active')?'Filtro aplicado':'Filtro eliminado')});content.querySelectorAll('.save-button').forEach(b=>b.onclick=()=>{b.textContent=b.textContent==='♡'?'♥':'♡';showToast(b.textContent==='♥'?'Guardado en favoritos':'Eliminado de favoritos')});if(page==='overview'){document.getElementById('heroSearch').onsubmit=e=>{e.preventDefault();const q=e.target.querySelector('input').value.trim();navigate('researcher');if(q){document.getElementById('chatInput').value=q;sendChat(q)}};document.getElementById('newsletterForm').onsubmit=e=>{e.preventDefault();showToast('Gracias. Revisa tu correo para confirmar la suscripción');e.target.reset()}}if(page==='researcher')bindChat();if(page==='library'){document.getElementById('paperSearch').oninput=e=>filterCards(e.target.value)}if(page==='observatory'){document.getElementById('countrySearch').oninput=e=>{document.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(e.target.value.toLowerCase()))}}}
function bindChat(){document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();sendChat(document.getElementById('chatInput').value)};document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>sendChat(b.textContent));document.getElementById('newChat').onclick=()=>navigate('researcher');document.getElementById('exportChat').onclick=()=>showToast('Conversación preparada para exportar')}
function sendChat(q){if(!q.trim())return;const intro=document.getElementById('chatIntro'),msgs=document.getElementById('chatMessages'),input=document.getElementById('chatInput');intro.style.display='none';msgs.style.display='block';msgs.innerHTML+=`<div class="chat-message user">${escapeHtml(q)}</div><div class="chat-message ai"><strong>✦ NINIA está analizando 12.486 fuentes…</strong><span class="typing">Buscando evidencia relevante, evaluando calidad y contrastando resultados.</span></div>`;input.value='';setTimeout(()=>{const last=msgs.querySelector('.chat-message.ai:last-child');last.innerHTML=`<strong>✦ Síntesis de evidencia</strong>La evidencia disponible indica que las intervenciones más efectivas combinan diseño seguro por defecto, alfabetización digital y mecanismos de reporte accesibles. Los efectos son mayores cuando existe coordinación entre escuelas, familias y plataformas <span class="citation">1</span>.<br><br>La calidad general de la evidencia es <b>moderada-alta</b>: hay consistencia entre revisiones sistemáticas, aunque persisten vacíos en países de ingresos medios y bajos <span class="citation">2</span> <span class="citation">3</span>.`;document.getElementById('sourceList').innerHTML=['UNICEF Innocenti · Evidence review 2026','OECD · Children & Young People Online','Nature Human Behaviour · Longitudinal study'].map((x,i)=>`<div class="source-card"><b>${i+1}. ${x}</b><small>${i===0?'Revisión sistemática':'Investigación primaria'} · Evidencia alta</small></div>`).join('');msgs.scrollTop=msgs.scrollHeight},900)}
function filterCards(q){document.querySelectorAll('.paper-card').forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(q.toLowerCase()))}
function escapeHtml(s){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
let toastTimer;function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}

document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();navigate(el.dataset.page)}));
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('aiOrb').onclick=()=>navigate('researcher');
document.getElementById('footerNewsletter').onsubmit=e=>{e.preventDefault();showToast('Gracias. Revisa tu correo para confirmar la suscripción');e.target.reset()};
const palette=document.getElementById('commandPalette');document.getElementById('commandBtn').onclick=()=>{palette.classList.add('open');palette.setAttribute('aria-hidden','false');setTimeout(()=>document.getElementById('globalSearch').focus(),30)};palette.onclick=e=>{if(e.target===palette)closePalette()};function closePalette(){palette.classList.remove('open');palette.setAttribute('aria-hidden','true')};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('commandBtn').click()}if(e.key==='Escape')closePalette();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='i'){e.preventDefault();navigate('researcher')}});document.querySelectorAll('.command-box [data-query]').forEach(b=>b.onclick=()=>{closePalette();navigate('researcher');const q=b.dataset.query;document.getElementById('chatInput').value=q;sendChat(q)});document.getElementById('globalSearch').onkeydown=e=>{if(e.key==='Enter'&&e.target.value.trim()){const q=e.target.value;closePalette();navigate('researcher');document.getElementById('chatInput').value=q;sendChat(q)}};
navigate(location.hash.slice(1)||'overview');
